language: php
php: '7.2'
services: mysql
addons:
  hosts:
    - db
install: skip
script:
  # inline commands
  - mysql -u root -e "CREATE USER 'app'@'%' IDENTIFIED BY 'ancake'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'app'@'%'"
  - mysql -u root -e "FLUSH PRIVILEGES"
  - mysql -u root -e 'CREATE DATABASE `ci`'
  # execute a SQL file
  - mysql -u app -pancake -h db -D ci < init.sql