language: php
php:
  - '5.6'
  - '7.0'
env:
  global:
    - EVERYWHERE=true
    - secure: wFEHP0wkdnSRxSbrH7U0wR+qXmzLzBqWn/d1bdE+EZ64poT8l4gotTRXZ7siYkPgOBPhDhpNF5zEQHQJSacBPQPt/PBg6ayciO5HbAD45lJE5Uv0Ff6uTGD6grJnF/XIdr0SidMHRJRJkt+H6y+rnWHStZfYj7kvSaFeJIYtwH+FIGa4J1ieO+m+3VTJjan4QFq+elFLg2D2zkPYRZVqzeYykwhXtYd9UFWEa8zox0WZSQ1eX0xHVWHMbe2Vw82WhJzWzhRd4xHuBNgsRgOe6k1uXZJZPqaoK93hAMLwHzEGflgAGjI8XAbG6SX7YLe99OadGOrIHx1ZgYVHAcOiLhuBJopAp6NuT9CXnMWvUPSu1jw2LElsoz2wKqhlOuzcG5o1inyrs9nqv7yUFessgzTRxIBAvHPNNPGiCaKsGmAuJXLIzRVjypoeAowTfft3tQ1JYlUFnzySBaY6Rui2U2dnUUy80WPTTldrdfMtJLA4XzP2bNsCDsgM5Z+iBSzBm+YKPl8/n2B0fChflAdVJ5D1BP8BCrKYlVLAWmySLz/pUaU/cFX10d6I1E542E3FgvKpWp1nb9OjeA4GzjvolwVb7NnywYlxNbOIdVu1t/XN65u4uCye8ohnz5H07Kxza7HbNubRNWh3vbiW/qJSL0lBjhT7oj0LRcL6TSmABmA=
  matrix:
    - DB=mysql
    - DB=pgsql
    - secure: DB=foo DWpZ9QEXrxua6Wdx3JPegV/1UuiVdldMpCJfy3Gvok6+WyZPUcAoGBNc63rgKwAamyhyGY/nFlekl80HielzgxKREaWt/XAW3UMoRXRTc0WNf2bP02TNCLudwCEzrTPiOoeENncgVPvbk4JHnpky218aqR5qdAlm1C+oqvBs/wiJ7Nf3HFZ0Yslkri5541lZghNwX2Ep+C6b/94tHPgClJRprI53QGw5ro8iZzt2T2xZKdlkC8DrM0q9XzvaFG257x9mTWFnByHDXt6MlDrrNcHMro6F4DAeQSsVL4T6THXilhrZH7qO8xn9xMCTuT1XOFo7Vh3LTomfwtdAjGxI/1CPESeqNfRBL1SdDqBQMO4DplY2XUYR3slWcJVhIu+AydfqhKzKQjvpcWusp6hx3xVqAot/1k+hJGT47R1x/N/gFMiwtddg8cgw0ngJXoB/+b8jhONtUKYOaKbfxI8zzSTjnG/5Vjt6753NrJkbWjSPLRirbWl8HR+/Tu8FLC7GIMQT2gfgNTSS3r/M8ox2O95doWaoOAIwezAFYIhrt0sB31NLUAfFUyQLM2VIQBMn9l3iUSoLpSQt5Nj82n2zKTsv8UHZ8BEIhlwfZQDE+6ndTAa4sqpPrmeUDncmjP+YeRmspM3YI5pjHbxoCAc+Afy45XSP4yIanzDwXVhSJXw= DB=bar
before_install: echo Let me tell you a $APP_SECRET from repository settings
install: echo Installing $DB
before_script: echo There is a $SHARED_SECRET and $ANOTHER_SECRET here
script: echo Connecting on $DB
