language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
cache:
  directories:
    - $HOME/.composer/cache
install: 
  - composer install --optimize-autoloader --prefer-dist
  - composer show
script: vendor/bin/phpunit