language: minimal
sudo: required
services: docker
env:
  global:
    - DOCKER_IMAGE=$DOCKER_USERNAME/keep-going
script:
- docker build -t $DOCKER_IMAGE .
- docker run --name app -d -p 4040:80 $DOCKER_IMAGE
- docker run --rm $DOCKER_IMAGE php -l /app/index.php
- docker ps -a
- curl -sS http://localhost:4040 | grep 'Just keep going!'
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: dockerfile
