language: php
php: '7.2'
services: mysql
install: skip
script:
  # create account (root's password is empty)
  - mysql -u root -e "CREATE USER 'app'@'%' IDENTIFIED BY 'secret'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'app'@'%'"
  # execute a SQL file
  - mysql -u root < init.sql
  - mysql -u root -e 'FLUSH PRIVILEGES'
  # use new account
  - mysql -u app -psecret -e 'SHOW DATABASES'
  - mysql -u app -psecret -e 'CREATE TABLE foo (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT)' ci
  - mysql -u app -psecret -e 'SHOW TABLES' ci
  - mysql -u app -psecret -e 'DESC foo' ci