language: php
php:
  - '5.6'
  - '7.0'
env:
  global:
    - EVERYWHERE=true
  matrix:
    - DB=mysql
    - DB=pgsql
before_install: echo Let me tell you a $APP_SECRET
install: echo Installing $DB
script: echo Connecting on $DB