language: php
php:
  - '5.6'
  - '7.0'
env:
  - DB=sqlite
  - SYMFONY_VERSION=4.1.* DB=mysql
  - DB=pgsql
matrix:
  include: 
    - php: '7.1'
      env: SYMFONY_VERSION=3.4.* DB=mysql
  exclude:
    - php: '7.0'
      env: SYMFONY_VERSION=4.1.* DB=mysql
before_install: env
install: 'echo "Installing DB: $DB"'
script: 'echo "Connecting to $DB"'